### ISSUE TITLE
Code for manipulating taxonomic hierarchy

### ISSUE THREAD

**Issue by richfitz** [wcornwell/taxonlookup#1]
Suppose you have a genus/family/order/table and you want to apply that to a vector of species.  Or you have binomial/genus/family/order table and you want to add a new species and have all the columns fill in.

Basically some way of working nicely with these sorts of data.

**Comment by richfitz** [comment]
Also, "is.nested" - are the given taxonomic levels perfectly nested?

**Comment by wcornwell** [comment]
```
get_family<-function(binomial){
  genus<-taxonlookup:::split_genus(binomial)
  return(plant_lookup()$family[match(genus,plant_lookup()$genus)])
}
```

isn't that the most common use case?

**Comment by wcornwell** [comment]
closing for now since `lookup_table` does the most common task, but will re-open is there is a specific function we should add
