### ISSUE TITLE
Test with new httr

### ISSUE THREAD

**Issue by richfitz** [wcornwell/taxonlookup#11]
> From: Hadley Wickham h.wickham@gmail.com
> Date: Wed, Jun 10, 2015, 9:48 AM
> Subject: httr 1.0.0
> To: 
> 
> Hi all,
> 
> I'm preparing to release httr 1.0.0. This is a big release because it
> replaces RCurl with curl, a modern binding to libcurl written by
> Jeroen Ooms. This should fix many strange and lingering bugs.
> 
> I've run R CMD check on all reverse dependencies, and notified you
> individually if I found any problems.  But I'd still recommend
> installing it (devtools::install_github("hadley/httr")) and testing
> yourself, just to make sure I haven't missed anything. Please let me
> know if you find any problems.
> 
> I'm planning to submit httr to CRAN on June 24.
> 
> Thanks!
> 
> Hadley

**Comment by wcornwell** [comment]
Problems:

``` R
> pl<-plant_lookup()
Error: key '0.3.1' not found, with error: Timeout was reached
In addition: Warning messages:
1: In curl::curl_fetch_disk(url, x$path, handle = handle) :
  progress callback must return boolean
2: In curl::curl_fetch_disk(url, x$path, handle = handle) :
  progress callback must return boolean
3: In curl::curl_fetch_disk(url, x$path, handle = handle) :
  progress callback must return boolean
4: In curl::curl_fetch_disk(url, x$path, handle = handle) :
  progress callback must return boolean
5: In curl::curl_fetch_disk(url, x$path, handle = handle) :
  progress callback must return boolean
6: In curl::curl_fetch_disk(url, x$path, handle = handle) :
  progress callback must return boolean
7: In curl::curl_fetch_disk(url, x$path, handle = handle) :
  progress callback must return boolean
8: In curl::curl_fetch_disk(url, x$path, handle = handle) :
  progress callback must return boolean
9: In curl::curl_fetch_disk(url, x$path, handle = handle) :
  progress callback must return boolean
10: In curl::curl_fetch_disk(url, x$path, handle = handle) :
  progress callback must return boolean
```

**Comment by richfitz** [comment]
Cool, thanks.  Will look into this tomorrow probably.

**Comment by wcornwell** [comment]
Looks everything works actually, just with this warning

``` R
1: In curl::curl_fetch_disk(url, x$path, handle = handle) :
  progress callback must return boolean
```

**Comment by richfitz** [comment]
I fixed that by reinstalling httr and curl.

**Comment by wcornwell** [comment]
I'm still getting the warnings

**Comment by sckott** [comment]
i get the same warnings with all updated versions of `curl` and `httr`

**Comment by wcornwell** [comment]
There might be a particular versions of `curl` and `httr` that still throw this warning, but `curl` 0.8.9000 and `httr` 1.0.0.9000 don't throw the warning.  But leaving open for now in case other people have this issue

**Comment by ccleung** [comment]
I'm getting the same warnings with `curl_0.9.1` and `httr_1.0.0`.

E.g., if I run:
`httr::GET('https://www.google.com', progress())`

I will see "There were 50 or more warnings (use warnings() to see the first 50)".

And here are the warnings (the same warning repeated):

```
50: In curl::curl_fetch_memory(url, handle = handle) :
  progress callback must return boolean
```

**Comment by wcornwell** [comment]
Yeah @ccleung it's been fixed here: https://github.com/hadley/httr/pull/252

But `httr` 1.0.0.9000 isn't up on CRAN.  If you load the github version  of `httr` the warning should go away.

**Comment by richfitz** [comment]
Confirmed working with hadley/httr, so any version >= 1.0.0.9000 should not have this problem.
