### ISSUE TITLE
sporadic error

### ISSUE THREAD

**Issue by gtaseski** [wcornwell/taxonlookup#12]
Error in file(file, mode) : cannot open the connection
In addition: Warning message:
In file(file, mode) :
  cannot open file '/Users/guytaseski/Library/Application Support/TaxonLookup/data/27dfd87685cad856f6ce808ab7b56b39.rds': No such file or directory

**Comment by wcornwell** [comment]
I've also had this on another machine, it's solved by restarting R, but it's a bit awkward...

**Comment by richfitz** [comment]
That's super weird.  Do you have any way of replicating it?  (sporadic errors are such a pain to debug).

**Comment by wcornwell** [comment]
try this:

``` R
> plant_lookup_delete()
> pl<-plant_lookup()
  |========================================================================================================================| 100%
Error in file(file, mode) : cannot open the connection
In addition: Warning message:
In file(file, mode) :
  cannot open file '/Users/willcornwell/Library/Application Support/taxonlookup/data/27dfd87685cad856f6ce808ab7b56b39.rds': No such file or directory
```

you might have to delete the package and install in the first time during that R session...

**Comment by richfitz** [comment]
Perfect: can reproduce here.

**Comment by richfitz** [comment]
OK, that should fix the error that Will found (plus added a test to catch any regressions).  Given the warning + error combo is the same as @gtaseski's _hopefully_ that's the same error.  Time will tell I guess.

**Comment by wcornwell** [comment]
Since this hasn't re-occurred, I think it's probably fixed.
