### ISSUE TITLE
Versions should be associated with the git sha

### ISSUE THREAD

**Issue by richfitz** [wcornwell/taxonlookup#13]
That's fairly straightforward to get the github interface; while we're doing things with a view to reproducibility and going all in on github we might as well do this.

So we'll keep the "0.1.0" interface; that's the human readable version.  But we'll provide some interface for indicating what sha that refers to so that one could write:

"We used version (v0.1.0 [a5ad1b8])" and people would be able to tell that was the _exact_ version.  This is only an issue because we can edit the releases.  At the same time, we can actually update the files on a release without that being reflected in the hash so that's no panacea either.

**Comment by richfitz** [comment]
OK, so the new datastorr version does provide facilities for retrieving that information, though it's not exposed at present.  Thoughts on if this is useful? @wcornwell @mwpennell?

**Comment by wcornwell** [comment]
i think the doi from the zenodo-github interface now solves this...
