### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by wcornwell** [wcornwell/taxonlookup#14]
MIT?
ping @richfitz @mwpennell

**Comment by richfitz** [comment]
MIT is fine with me.

**Comment by wcornwell** [comment]
also need to add it to https://github.com/richfitz/phyndr ?

**Comment by richfitz** [comment]
I already licenced that under BSD (2 clause) https://github.com/richfitz/phyndr/blob/master/DESCRIPTION#L6

**Comment by wcornwell** [comment]
do we need anything here:
https://github.com/richfitz/phyndr/blob/master/LICENSE ?

**Comment by richfitz** [comment]
yeah, if you could follow the pattern in phyndr that'd be best, as traitfill is an R package - see [this issue](https://github.com/ropensci/ecoretriever/issues/18) for details, or I can sort it out at some point.

**Comment by wcornwell** [comment]
ok i'll fix it.
