### ISSUE TITLE
problem with keys?

### ISSUE THREAD

**Issue by wcornwell** [wcornwell/taxonlookup#17]
``` R
 pl<-plant_lookup()
Error: key 'wcornwell/taxonlookup' ('objects') not found, with error: client error: (401) Unauthorized
```

any idea? @richfitz

**Comment by wcornwell** [comment]
should probably be traitecoevo/taxonlookup instead of wcornwell/taxonlookup somewhere

**Comment by richfitz** [comment]
Nope, looks like I assumed all entrypoints I used in the read only interface didn't need keys.  Will get onto that but travelling for the next week :(

**Comment by wcornwell** [comment]
OK.  Also check the same error from Travis CI

**Comment by richfitz** [comment]
Yeah. I assumed that was the wrong github key but obviously not. Will see what I can do but I thought that I'd tested that it worked....

**Comment by richfitz** [comment]
OK, I believe I have this fixed.  Can you check and close if the fix works?

**Comment by richfitz** [comment]
Fixed on travis

**Comment by wcornwell** [comment]
works for me!  :beers:
