### ISSUE TITLE
Higher-level lookup for unresolved genera

### ISSUE THREAD

**Issue by rossmounce** [wcornwell/taxonlookup#22]
I would like to know the high-level taxonomy of names that are Unresolved e.g. _Acetosella_ http://www.theplantlist.org/tpl1.1/search?q=Acetosella

```
plant_lookup_version_current()
[1] "1.1.1"
lookup_table(c("Pinus","Acetosella"),missing_action="NA")
       genus   family   order       group
1      Pinus Pinaceae Pinales Gymnosperms
2 Acetosella     <NA>    <NA>        <NA>
```

I would instead expect / like this to be the output

```
lookup_table(c("Pinus","Acetosella"),missing_action="NA")
       genus   family   order       group
1      Pinus Pinaceae Pinales Gymnosperms
2      Acetosella Oxalidaceae Oxalidales Angiosperms
```

_Acetosella_ may not be the best example of this, it has synonyms known to TPL. 

Perhaps, _Toddavaddia_ is a better example: it has known higher taxonomy but is not a known synonym of anything else by TPL -- thus it seems very legitimate to ask directly what _Toddvaddia_ is in terms of higher taxonomy. http://www.theplantlist.org/1.1/browse/A/Oxalidaceae/Toddavaddia/

**Comment by wcornwell** [comment]
Acetosella has unresolved species in 2 families, so right now both are getting dropped to preserve the one-to-one genus-to-family mapping.   Probably TPL 1.2 will work that out, but not sure what to do on that in the interim...

Toddavaddia looks like a different issue, checking on this...

**Comment by wcornwell** [comment]
I think Toddavaddia is working...

``` R
> lookup_table(c("Pinus","Toddavaddia"),missing_action="NA")
        genus      family      order       group
1       Pinus    Pinaceae    Pinales Gymnosperms
2 Toddavaddia Oxalidaceae Oxalidales Angiosperms
```

**Comment by rossmounce** [comment]
"Acetosella has unresolved species in 2 families" -- wow. Okay, I see why this hasn't been implemented then. Complicated!  Even so, I would assume those families are within the same Order. Perhaps for complicated cases the Order and the high-level group could still be given?
