### ISSUE TITLE
Genera with TPL-accepted Bryophyte species in different families

### ISSUE THREAD

**Issue by rossmounce** [wcornwell/taxonlookup#25]
According to the TPL1.1. website I'm seeing that several 'accepted' Bryophyte genera are in two different families e.g.  
Pleuridium, Mnium, Micromitrium, Mastigophora, Lamprophyllum, Hypopterygium

For a really specific individual 2 species example:

_Pleuridium algesiriense_ appears to be in Archidiaceae http://www.theplantlist.org/1.1/browse/B/Archidiaceae/Pleuridium/

whilst

_Pleuridium acuminatum_ appears to be in Ditrichaceae
http://www.theplantlist.org/1.1/browse/B/Ditrichaceae/Pleuridium/

This isn't reflected in `taxonlookup` output (see below, both are given as Ditrichaceae). How did you decide which is the winning family? 

Happy you've done this (it's more phylogenetically-sane), but it perhaps needs documentation/justification (if it was deliberate?). If I missed it, please just point me to it.

```
>plant_lookup_version_current()
[1] "1.1.1"
> lookup_table(c("Pinus ponderosa","Pleuridium algesiriense","Pleuridium acuminatum"),missing_action="NA",by_species=TRUE)
                                   genus   family   order       group
1 Pinus ponderosa Pinus Pinaceae Pinales Gymnosperms
2 Pleuridium algesiriense Pleuridium Ditrichaceae Undeter_peristomate_moss Bryophytes
3 Pleuridium acuminatum Pleuridium Ditrichaceae Undeter_peristomate_moss Bryophytes
```

**Comment by wcornwell** [comment]
Tricky one.  Taxonlookup is built around the one-to-one genus-to-family (Linnean) mapping, and I think the fact that TPL has the same genera in different families has to be seen as a bug in their database.

Moreover, the package only distributes a genus-to-family lookup, so there isn't any technical way to get Pleuridium algesiriense and Pleuridium acuminatum to show up in different families.  

Given that the whole package is constrained to follow proper Linnean rules, right now this is the behavior for dealing with issues with when TPL doesn't follow those rules:
1. For conflicts among accepted species it points to the family with more accepted species.  This seemed to solve a somewhat common TPL bug where there was one moss species with the genus mistakenly listed as Pinus or something like that, and we didn't want to drop the clearly legitimate genus Pinus.  
2. For conflicts in which some species are accepted and others unresolved, it goes with the family of the accepted species.
3. For conflicts where all the species are unresolved it drops the genus entirely from both (or in some cases all three) families

The full list of genus--family pairs that get dropped based on this is [here](https://github.com/traitecoevo/taxonlookup/blob/master/source_data/badGeneraFamilyPairs.csv). 

Happy to change this behavior if there is another option that makes more sense.

BTW, most of these are problems with Bryophytes, and in the medium term, I'd like to solve most of these problems by moving the bryophytes to a new classification which seems to be a bit more rigorous on these issues (see #15), but that's waiting for their latest revision and is probably not going to happen fast.

**Comment by rossmounce** [comment]
Thanks for the fantastic answer. I think what you've done here is exactly what is needed: one-to-one genus-to-family (Linnean) mapping!

**Comment by wcornwell** [comment]
Cool.  Should probably move this info to the documentation at some point...

**Comment by wcornwell** [comment]
moved to documentation..
