### ISSUE TITLE
_Austroderia_ N.P. Barker & H.P. Linder missing/not found in plant_lookup.csv

### ISSUE THREAD

**Issue by rossmounce** [wcornwell/taxonlookup#31]
Recently erected (2010) and present in TPLv1.1 albeit as "unresolved" I don't see why it shouldn't be included...

http://www.theplantlist.org/tpl1.1/search?q=Austroderia

Perhaps this is a more general problem with "unresolved genera" where none of the species are accepted by TPLv1.1 ?

**Comment by wcornwell** [comment]
I think the general probably is that some "unresolved" genera (not all) aren't showing up here: http://www.theplantlist.org/1.1/browse/A/Poaceae/
or more importantly in the family level csv.

There is a distinction they make [here](http://www.theplantlist.org/1.1/about/#limitations) about *unresolved* versus *unplaced* but it's not clear exactly how that applies to the cases you've found

**Comment by wcornwell** [comment]
closed in favor of #37
