### ISSUE TITLE
Unresolved but missing genus: Eufragia

### ISSUE THREAD

**Issue by rossmounce** [wcornwell/taxonlookup#34]
I can see this one is more obviously contentious

But _Eufragia_ type species: _Eufragia latifolia_ Griseb. 1844

is present on TPLv1.1 with 5 unresolved species http://www.theplantlist.org/tpl1.1/search?q=Eufragia

It might be _Euphrasia_ ? or perhaps _Parentucellia latifolia_ Caruel ?

Nevertheless, for consistency, shouldn't this package report TPL data, except for AP-web modifications to higher-classification?

**Comment by wcornwell** [comment]
closed in favor of #37
