### ISSUE TITLE
Misattribution of Adelanthus (Bryophytes) to the Angiosperms

### ISSUE THREAD

**Issue by rossmounce** [wcornwell/taxonlookup#38]
First of all, let me start by saying this one isn't an issue of `taxonlookup`. The error is entirely TPL's. Nonetheless you might want to fix this one...

In `taxonlookup` 's plant_lookup.csv file, faithfully reproducing what is posted on the TPL website  "The genus Adelanthus is in the family Icacinaceae in the major group Angiosperms" http://www.theplantlist.org/1.1/browse/A/Icacinaceae/Adelanthus/ 

The story here is there are (or were) two _Adelanthus_ 's, one a bryophyte genus, the other an angiosperm genus. The Angiosperm one is the rejected name http://www.tropicos.org/Name/40032149 
and it was replaced by _Pyrenacantha_.
 
http://www.theplantlist.org/1.1/browse/A/Icacinaceae/Adelanthus/ lists only the species of the bryophyte genus, yet they are mis-attributed as angiosperms.
All the species of the angiosperm genus are correctly at Pyrenacantha http://www.theplantlist.org/1.1/browse/A/Icacinaceae/Pyrenacantha/ 

At the macro-level, the effect of this is that plant_lookup.csv & TPL have +18 too many accepted Angiosperm species (including 18 bryophytes as angiosperms), and the bryophytes have -18 species not assigned to them.

I realise +/- 18 species on a total count of 304,419 accepted angiosperm species might not be worth bothering to fix but I thought I'd point it out. I do wish they could stick TPL on github so we could just fix these things ourselves with moderated edits!

**Comment by wcornwell** [comment]
sorry for the slowness on this...somehow missed these issues.  will have a look

**Comment by wcornwell** [comment]
removing the Adelanthus - Icacinaceae link.  Not sure about what to do about Adelanthaceae.  some of the Adelanthus species look like they may be synonyms for accepted species in Calyptrocolea.  probably needs an bryologist to really clean that all up.

**Comment by wcornwell** [comment]
on the other hand, Adelanthus bisetulus looks to be a good (moss) species.

**Comment by wcornwell** [comment]
closed in favor of #43

**Comment by wcornwell** [comment]
for the moment, going with 10 species, following tropicos
