### ISSUE TITLE
Missing the genus Amblytropis in the family Daltoniaceae (Bryophytes)

### ISSUE THREAD

**Issue by rossmounce** [wcornwell/taxonlookup#39]
Another interesting homonym-related issue.

This time the TPL website has it partially-correct and plant_lookup.csv is somehow in error.

There are two separate Amblytropis genera recognised by TPL:
http://www.theplantlist.org/1.1/browse/B/Daltoniaceae/Amblytropis/
http://www.theplantlist.org/1.1/browse/A/Leguminosae/Amblytropis/

plant_lookup.csv only contains "Amblytropis" as attributed to Leguminosae, which is actually the illegitimate one of the two http://www.tropicos.org/Name/40011645 

Again, TPL is guilty of double-counting species here because correct names are all there as accepted on TPL too at _Gueldenstaedtia_: http://www.theplantlist.org/1.1/browse/A/Leguminosae/Gueldenstaedtia/

so -4 for Angiosperms
and +4 for Bryophytes in terms of species

and -1 for Angiosperms and +1 for Bryophytes in terms of genera

**Comment by wcornwell** [comment]
sorry for the slowness--somehow missed this issues on my feed.  will have a look.

**Comment by wcornwell** [comment]
it was backwards here: https://github.com/traitecoevo/taxonlookup/blob/master/source_data/badGeneraFamilyPairs.csv

will fix shortly

**Comment by wcornwell** [comment]
fixed in https://github.com/traitecoevo/taxonlookup/commit/d9af291782dabfb89f0f6bc9a451ac3b0a97a0e6
