### ISSUE TITLE
Add higher order taxonomy

### ISSUE THREAD

**Issue by richfitz** [wcornwell/taxonlookup#4]
Can get much of this from the woodiness thing, but getting the Angio/Gymo/Fern split on here would be particularly useful.

**Comment by wcornwell** [comment]
Angio/Gymo/Fern split added, but still could add some more stuff from http://datadryad.org/resource/doi:10.5061/dryad.63q27

**Comment by wcornwell** [comment]
Should this be a function that syncs this table with http://datadryad.org/bitstream/handle/10255/dryad.59001/Spermatophyta_Genera.csv?sequence=2 ?

**Comment by richfitz** [comment]
Closed in 88a9aed
