### ISSUE TITLE
Schroeterella misattributed as in Angiosperms, should be Bryophytes

### ISSUE THREAD

**Issue by rossmounce** [wcornwell/taxonlookup#40]
Yet another homonym-related error.

The legitimate usage is in the bryophytes, by prior publication
The illegimate usage is in angiosperms http://www.tropicos.org/Name/40032845

On both TPL http://www.theplantlist.org/tpl1.1/record/tro-35149672 and plant_lookup.csv, _Schroeterella_ is mistakenly assigned to the family Zygophyllaceae in the major group Angiosperms.

It should instead be assigned: Sematophyllaceae,Sematophyllaceae,Undeter_peristomate_moss,Bryophytes

**Comment by wcornwell** [comment]
removing from Zygophyllaceae.  haven't figured out how to add it to Sematophyllaceae yet though...

**Comment by wcornwell** [comment]
closed in favor of #43

**Comment by wcornwell** [comment]
looks like two species in the genus:
http://www.bioone.org/doi/abs/10.1639/0007-2745-116.2.146
