### ISSUE TITLE
Myrinia misattributed as in Angiosperms, should be Bryophytes

### ISSUE THREAD

**Issue by rossmounce** [wcornwell/taxonlookup#41]
Yet another homonym-related error.

The legitimate usage is in the bryophytes
The illegimate usage is in angiosperms http://www.tropicos.org/Name/40024361

On both TPL e.g. http://www.theplantlist.org/tpl1.1/record/tro-35171180 and plant_lookup.csv, Myrinia is mistakenly assigned to the family Onagraceae in the major group Angiosperms.

It should instead be assigned: 
Myriniaceae,Myriniaceae,Undeter_peristomate_moss,Bryophytes

incidentally it's also the type genus of the family(!!!)

so -4 angiosperms, +4 bryophytes in terms of species-counting
and -1 angiosperm and +1 bryophyte in terms of genera-counting

PS I found these homonym-issues by cross-checking the large genus-rich phylogeny from Hinchcliff & Smith (2014) with TPL/_taxonlookup_. Phylogeny helping to spot errors in taxonomies - it's usually vice versa! http://datadryad.org/resource/doi:10.5061/dryad.450qq

**Comment by wcornwell** [comment]
removing from Onagraceae for the moment, but haven't got a way to get it into mosses yet.  will work on that

cool idea to cross check with a big phylo!

**Comment by wcornwell** [comment]
closed in favor of #43

**Comment by wcornwell** [comment]
tropicos has it in Fabroniaceae...so putting it there for now...
