### ISSUE TITLE
Add a switch for APWeb families versus Plant list families

### ISSUE THREAD

**Issue by wcornwell** [wcornwell/taxonlookup#9]

**Comment by richfitz** [comment]
Is this in building the list or in loading it?

**Comment by wcornwell** [comment]
Peter was complaining about some of the plant list family definitions.  

Maybe the easiest thing is to just add a column so that we don't mess up our dataset versioning system?

**Comment by richfitz** [comment]
Sure; `family.apg` perhaps.  And then add a switch to the loading function to use it, but turn off by default.  This is also where semantic versioning comes in useful; we can consider this a feature (update the middle number) or a breaking change and update the first.

**Comment by wcornwell** [comment]
Looks like the family lists actually line up--possibly the issue is more about which genera are in each family, and can't really fix that...I've left in some commented out code for if APweb and TPL family lists diverge in the future but not necessary at the moment.

**Comment by richfitz** [comment]
If Peter can furnish us with a list of edits I can apply that as a patch easily enough.

**Comment by wcornwell** [comment]
done
